<img src='https://th.bing.com/th/id/OIP.0mtPy_tJkhR2cw2LACoGBwHaEK?pid=ImgDet&rs=1'>

'''NumPy is a Python Library. It stands for 'Numerical Python'.
It is a library consisting of multidimensional array objects.
'''


> Numpy array vs List



In [ ]:
d='''
Python List:

Lists are the inbuilt data structure of python.
We can store elements of different types in the list.
Items in the list are enclosed between square brackets and separated by commas.
We can even nest lists with other data structures like lists, dictionaries, tuples, etc.

Python Array:

Arrays are not the in-built data structure readily available in python.
We must import the array from the 'array' or 'numpy' module.
Array stores elements of similar types. If we try to store elements of different types, it will throw an error.
We can only store elements of the same types in the array.

'''


<img src="https://res.cloudinary.com/hmqtkdlno/image/upload/v1592596177/utzc1ntfyu0modaxbzte.png">

<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png">

In [ ]:
# for installing the numpy
!pip install numpy


#import numpy module with alias np
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a = np.array([1,2,3,4,'a'])

In [ ]:
# print a
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

## Dimensions in Arrays


Numpy array can be of n dimentions

Lets create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

<p style='text-align: right;'> 3 points </p>


In [ ]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimension? Use ndim attribute on each variable to check its dimension

In [ ]:
#print dimentions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3




Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print(c.dtype)
print(d.dtype)

int32
int32


Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
len(d)

2

### Creating Numpy array


There are multiple ways to create numpy array. Lets walk over them

1. Using arrange() function <br>
<p style='text-align: right;'> 8 points </p>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameters
np.arange(1,11,2)

array([1, 3, 5, 7, 9])



2. Using eye Function <br>


In [ ]:
# create numpy array using eye function with 3 as passed parameter
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Wohoo! eye return a 2-D array with ones on the diagonal and zeros elsewhere.

3. Using zero function<br>


In [ ]:
#create a numpy array using zero function with (3,2) as passed parameter takes default float
np.zeros((3, 5),dtype='int') # default float

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Zero function returns a new array of given shape and type, filled with zeros.

4. Using ones Function <br>


In [ ]:
#create a numpy array using ones function with (3,2) as passed parameter
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

You noticed! ones function returns a new array of given shape and type, filled with ones.

5. Using full Function<br>


In [ ]:
#create a numpy array using full function with (3,2) and 2 as passed parameter
np.full((2, 3), 14,dtype=int)

array([[14, 14, 14],
       [14, 14, 14]])

<img src="https://backtobazics.com/wp-content/uploads/2018/08/numpy-eye-full-methods.jpg">



6. Using diag function<br>


In [ ]:
#create a numpy array using diag function passing a list [1,2,3,4,5]
x = [1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])



## Numpy Reshape



Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

<p style='text-align: right;'> 6 points </p>


<img src="https://backtobazics.com/wp-content/uploads/2018/08/numpy-reshape-examples.jpg">

In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [ ]:
# Reshape x with 2 rows and 8 columns
n=x.reshape((8,2)) # 1d
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [ ]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [ ]:
# convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ravel-function-image-1.png">

In [ ]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
print(x)
x.reshape((2,8))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ndarray-flatten-function-image-1.png">

In [ ]:
# Flattening x convert array into one dimensional
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## NumPy Array Indexing


Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

<p style='text-align: right;'> 4 points </p>


In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

In [ ]:
# Get third element in array a
a[2]

In [ ]:
#Print 3rd, 5th, and 7th element in array a
a[0:7:2]

Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
# print the 3rd element from the 3rd row of a
a[2,2]

<img src="https://qph.fs.quoracdn.net/main-qimg-82a0721a240faf8b7aa563492f4ccadf">

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[1][1][2]

12

Great job!
So now you have learned how to to indexing on various dimentions of numpy array.

## NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

    1. We pass slice instead of index like this: [start:end].
    2. We can also define the step, like this: [start:end:step].
    3. If we don't pass start its considered 0
    4. If we don't pass end its considered length of array in that dimension
    5. If we don't pass step its considered 1

<p style='text-align: right;'> 5 points </p>


1. **Array slicing in 1-D array.**

In [ ]:
arr=np.arange(1,11)
arr

In [ ]:
# Slice elements from 1st to 5th element from array arr:
arr[0:5]


In [ ]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

In [ ]:
# Slice elements from the beginning to index 5 (not included) in array arr:
arr[0:5]

In [ ]:
# Print every other element from index 1 to index 7:
arr[1:7:2]

In [ ]:
# Return every other element from the entire array arr:
arr[0:10:2]

In [ ]:
# Print array a
a

In [ ]:
# In array 'a' print index 2 from all the rows :
arr[2]

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[0:,1:]

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view



<p style='text-align: right;'> 7 points </p>


In [ ]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# assign x2 = x1
x2 = x1 # view

In [ ]:
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Ok now you have seen that both of them are same

In [ ]:
# change 1st element of x2 as 10
x2[0] = 10

In [ ]:
#Again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
print(id(x1))
print(id(x2))

2276565491600
2276565491600


Wait a minute. Just check your above result on change of x2, x1 also got changed. Why?

Lets check if both the variables shares memory. Use numpy shares_memory() function to check if both x1 and x2 shares a  memory.


In [ ]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
2276565491600
2276565491600


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [ ]:
# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

True

In [ ]:
#Change 1st element of x3=100
x3[0] = 100

In [ ]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

x4 = np.copy(x1)

In [ ]:
# Change the last element of x4 as 900
x4[-1] = 900

In [ ]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.



In [ ]:
#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)

2276565491600
2276565489776


False

You see! x1 and x4 don't share its memory.

So with all our outputs we can takeaway few points:

    1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

    2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

    3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## More operations on Numpy

**1. Applying conditions**



<p style='text-align: right;'> 5 points </p>


In [ ]:
#print a
a

array(10)

We are going to use 'a' array for all our array condition operations.


In [ ]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 3


True

In [ ]:
# Get a list with all elements of array 'a' grater than 3
a[a > 3]

array([10])

In [ ]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 3) & (a < 6)]

array([], dtype=int32)

In [ ]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1 == x4
# print(x1)
# print(x4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

You can see in above output that the last element is not same in both x1 and x4

Well done so far.

Lets check how to transpose an array

**2. Transposing array**


In [ ]:
# Print Transpose of array 'a'
print(a.transpose())
#print array 'a'
print("-----------------")
print(a)

10
-----------------
10


In above output all the rows became columns by transposing

**3. hstack vs vstack function**



Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns


<img src="https://images4.pianshen.com/908/91/91b34f7c4a78a2e22d6b7ba0a7186584.png">

In [ ]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [ ]:
#stack x1 and x4 along rows
np.hstack((x1, x4))

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

## Adding, Insert and delete Numpy array


<p style='text-align: right;'> 3 points </p>


Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1, 4, x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2
print(x2)
np.delete(x2, 0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Did you see? 2 value is deleted from x2 which was at index position 2

## Mathmatical operations on Numpy array



<p style='text-align: right;'> 8 points </p>


In [ ]:
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# print trigonometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [ ]:
np.sin(0)

0.0

In [ ]:
np.tan(0)

0.0

In [ ]:
(np.sin(a))/(np.cos(a))

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [ ]:
# print trigonometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [ ]:
# Print exponential value of each elements of a
np.exp(a) # **

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
# print total sum of elements of a
np.sum(a)

45

In [ ]:
# Print sum in array a column wise
np.sum(a, axis=1)

array([ 6, 15, 24])

In [ ]:
# Print sum in array a row wise
np.sum(a, axis=0)

array([12, 15, 18])

<img src="https://th.bing.com/th/id/R.9230ced1c11e813fb069ddcac6566fdf?rik=C1ohvKa4zik%2b4w&riu=http%3a%2f%2flh5.ggpht.com%2f-1oz5Rz51kmo%2fU_xUcCLo4KI%2fAAAAAAAAB1g%2fyzk9KPcJ-NM%2fmeasures%25252520of%25252520central%25252520tendency_thumb%2525255B13%2525255D.gif%3fimgmax%3d800&ehk=%2bBH1cRV14pqT3nEfMTOkYImdkFZDlqR6fFJ1eM%2bKAcw%3d&risl=&pid=ImgRaw&r=0">

In [ ]:
# print median of array a
np.median(a)

In [ ]:
# print mean of array a
np.mean(a)


<img src="https://th.bing.com/th/id/R.a2c52d7062fa0de9d9df6032b7e0da75?rik=ptW1AfWGEGJi%2fQ&riu=http%3a%2f%2fimage.slideserve.com%2f274561%2fformula-for-standard-deviation-l.jpg&ehk=VClOXZLFkcG6HPqdc7rRMwWSMjYJ2T%2fGN1A8smQgV5Q%3d&risl=&pid=ImgRaw&r=0">

In [ ]:
# print standard deviation of array a
np.std(a)

2.581988897471611

In [ ]:
#print largest element present in array a
np.max(a)

9

In [ ]:
# print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

<p style='text-align: right;'> 4 points </p>


In [ ]:

# Create a numpy array
arr = np.array([[12,14,17,19,24,27,35,38]])

# Use numpy.where() with 1 Dimensional Arrays
arr1 = np.where(arr > 17)
print(arr1)



(array([0, 0, 0, 0, 0], dtype=int64), array([3, 4, 5, 6, 7], dtype=int64))


In [ ]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [ ]:
import keyword
print(keyword.kwlist)


['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
